### ISSUE TITLE
wrong mode getting saved after "get" from gqrx 2.7

### ISSUE THREAD

**Issue by maurizioandreotti** [Marzona/rig-remote#100] opened 2017-09-06 13:51 UTC
HI. 
I am using rig-remote (latest version as of today) with gqrx 2.7 for its scanning and bookmarking features.

I found this: when i do a GET from gqrx I get in the "mode" field a text like this:
"AM^\10000" 

If I ADD it in the bookmark, rig-remote add it and keep working apparently fine.

when then I close rig-remote and reopen it, it is not able to load reading any bookmark at anymore and provides an error "invalid bookmark in position xyz"

I have checked the bookmark file and it contains a CRLF just after "AM" (i.e. in the middle of the line)

Workaroud found:
the issue is easy to avoid paying attention after each GET to edit "AM*10000" to match "AM" in the list in the combo box, in this case the bookmarks are correctly saved and restered at rig-remote reopening.

**Comment by Marzona** [comment] 2017-09-17 11:05
Hello,
I am not able to reproduce the problem, it may be related to gqrx2.7 (which I have to install, I have gqrx2.6). Can you please provide:

- OS you are using
- screenshot of the problem (if possible)

thanks

**Comment by Marzona** [comment] 2017-09-17 11:07
Question: is this happening only with AM or it is happening in other modes aswell?

**Comment by Marzona** [comment] 2017-09-17 11:38
reproduced with gqrx 2.8 built from source.
The issue happens from gqrx2.7 upwards. This may not be an issue of rig-remote. If I talk directly to the GQRX socket on GQRX 2.6 I get: 
<pre>
marzona@rubberduck:~$ telnet localhost 7357
Trying 127.0.0.1...
Connected to localhost.
Escape character is '^]'.
m
WFM_ST
</pre>
While on GQRX 2.8 I get:

<pre>
marzona@rubberduck:~$ telnet localhost 7356
Trying 127.0.0.1...
Connected to localhost.
Escape character is '^]'.
F
RPRT 1
f
98000000
m
FM
10000
</pre>

I'll go through the release notes of GQRX to check if this is the expected behavior or not. After that I will code a workaround and/or file a request to GQRX.

regards

**Comment by Marzona** [comment] 2017-09-20 05:40
as per https://github.com/csete/gqrx/issues/560 the expected behavior changed over the releases and I have to update the code in my side.

**Comment by maurizioandreotti** [comment] 2017-09-20 08:22
ciao.  sorry I was away. I don't have the Linux PC with me now.
I was using the latest version compiled from sources

the issue was for all modes.  When I was taking the config from the sdr app
the string was just coming in this other way.



Il 20 set 2017 07:40, "Simone Marzona" <notifications@github.com> ha
scritto:

**Comment by Marzona** [comment] 2017-09-20 09:18
No problem.

as per confirmation of csete this is the new expected behavior and I will update my code accordingly.

**Comment by Marzona** [comment] 2017-09-30 08:51
fixed in : https://github.com/Marzona/rig-remote/pull/101

pull merged in master branch.

**Closed as completed by Marzona** 2017-09-30 08:51 UTC
Labels: enhancement
